### ISSUE TITLE
最后一步：运行文件生成的二进制文件？

### ISSUE THREAD

**Issue by T-melon** [Youggls/Compiler#21]
上一步的build里的文件是这些
![image](https://user-images.githubusercontent.com/71576022/205210018-c1b22308-3382-4e14-8da2-6ae32503b737.png)

尝试运行单个.o文件报错说不是可以运行的格式cannot execute binary file: Exec format error，尝试将所有的.o文件链接起来也报错，提示format elf32-i386 (basic_loop.o) to format elf64-x86-64 (array.o) is not supported，即不支持将elf32-i386（basic_loop.o）格式化为elf64-x86-64（array.o）格式
不知道应该如何解决，如果您能在百忙之中帮忙解答我的疑惑，将不胜感激

**Comment by Youggls** [comment]
你好
1. .o格式的文件并不是可执行文件，需要连接器链接后才能运行
2. build 文件夹中的文件和目录，`io/` 目录和 `parser` 文件分别为io库和编译器（生成汇编文件），`test/` 文件夹下是几个测试用例，这些用例是相互独立的程序。
3. 给出的错误看起来应该是没有安装交叉运行库，请安装 `gcc-multilib` 这一库，具体参考 README。
4. 将这些例子编译的实例可以参考 `build/` 目录下的 `Makefile` 文件。

希望对你有帮助

**Comment by T-melon** [comment]
不好意思，还想具体问一下此时应当执行什么命令？
就是连接器链接，还有具体运行命令？
库安装了，或许是我尝试的运行命令错误了。

**Comment by Youggls** [comment]
以 `swap.o` 为例， 可以使用 `gcc -o swap swap.o io/asm_io.o -m32` 链接。
更多内容可以参考 [Makefile](https://github.com/Youggls/Compiler/blob/master/example/Makefile)

**Comment by T-melon** [comment]
您好，我成功生成了可执行文件swap，但是运行没有反应，不应当是在build目录下面直接执行`./swap`吗？
链接：
![image](https://user-images.githubusercontent.com/71576022/205428826-687787c8-8944-4043-b95a-a0eda46ae49e.png)
运行：
![image](https://user-images.githubusercontent.com/71576022/205428758-a08b2493-1877-45f6-92fe-f8c322cc3c6b.png)

**Comment by Youggls** [comment]
> 您好，我成功生成了可执行文件swap，但是运行没有反应，不应当是在build目录下面直接执行`./swap`吗？
> 链接：
> ![image](https://user-images.githubusercontent.com/71576022/205428826-687787c8-8944-4043-b95a-a0eda46ae49e.png)
> 运行：
> ![image](https://user-images.githubusercontent.com/71576022/205428758-a08b2493-1877-45f6-92fe-f8c322cc3c6b.png)
> 

已经有输出结果了，看下面那行开头已经是2332了，只不过没有输出换行符。

**Comment by T-melon** [comment]
谢谢您，问题解决了
