### ISSUE TITLE
使用gcc编译lex.yy.c文件时出现错误

### ISSUE THREAD

**Issue by aililuola** [Youggls/Compiler#23]
yanxinyu@yanxinyu-virtual-machine:/mnt/hgfs/share$ flex lexer.l
yanxinyu@yanxinyu-virtual-machine:/mnt/hgfs/share$ gcc lex.yy.c -o scanner
lexer.l:3:10: fatal error: grammar.tab.h: 没有那个文件或目录
    3 | #include "grammar.tab.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
yanxinyu@yanxinyu-virtual-machine:/mnt/hgfs/share$

**Comment by Youggls** [comment]
请遵循 `Makefile` 文件的步骤进行编译。
